### ISSUE TITLE
Could not to connect to server(ConnectException)

### ISSUE THREAD

**Issue by freshpomelo** [JaneliaSciComp/workstation#3] opened 2019-09-30 02:59 UTC
Hi all,

I've installed the workstation and jacs-cm on "Docker Compose Deployment" mode on my own Mac.

But when I start the workstation application, it showed an error below:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/10544528/65846236-b5a6e700-e36f-11e9-8922-060948b99a5c.png">

When I installed jacs-cm, I followed the instruction in "Docker Compose Deployment" mode and set the HOST1 to localhost.
<img width="558" alt="image" src="https://user-images.githubusercontent.com/10544528/65846672-1f73c080-e371-11e9-804e-08cb300424c4.png">

Any advice would be greatly appreciated!

**Comment by freshpomelo** [comment] 2019-09-30 05:52
Hi all,
Sorry, I made a silly mistake which I didn't start the docker container.
The workstation connect to the server successfully, but it has the same issue with https://github.com/JaneliaSciComp/jacs-cm/issues/5#issue-495714104
I didn't input the right username and password, which should be "root/root" according to jacs-cm/docs/ComposeDeployment.md instruction.
<img width="382" alt="image" src="https://user-images.githubusercontent.com/10544528/65852709-8ef5aa00-e389-11e9-9782-5edcee266b18.png">

**Comment by krokicki** [comment] 2019-09-30 17:35
Closing since this is a duplicate of the other issue

**Closed by krokicki** 2019-09-30 17:35 UTC
